apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/keerthibala312/devops-demo:prod
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: production
            - name: APP_VERSION
              value: prod
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
